apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-shared
spec:
  description: Project for shared cluster system components
  sourceRepos:
    - "git@github.com:NucleusEngineering/dogcat-applications.git"
  destinations:
    - namespace: "*"
      server: "https://kubernetes.default.svc"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-shared
spec:
  destination:
    namespace: "argocd"
    server: "https://kubernetes.default.svc"
  project: cluster-shared
  source:
    path: "cluster-shared"
    repoURL: "git@github.com:NucleusEngineering/dogcat-applications.git"
    targetRevision: "HEAD"
  syncPolicy:
    automated: {}
