apiVersion: gcp.nvoss.demo.altostrat.com/v1alpha1
kind: IAPService
metadata:
  name: argocd-server-iap
spec:
  port: 8080
  targetPort: 8080
  selector:
    "app.kubernetes.io/name": "argocd-server"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server
  annotations:
    "cert-manager.io/cluster-issuer": "letsencrypt"
spec:
  rules:
  - host: "argocd.shared.dogcat.nvoss.demo.altostrat.com"
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: argocd-server-iap
            port:
              number: 8080
  tls:
  - hosts:
      - "argocd.shared.dogcat.nvoss.demo.altostrat.com"
    secretName: argocd-server-tls
