apiVersion: gcp.nvoss.demo.altostrat.com/v1alpha1
kind: WorkloadIdentity
metadata:
  name: argocd-server
spec:
  roles: ["roles/container.viewer"]
---
apiVersion: gcp.nvoss.demo.altostrat.com/v1alpha1
kind: WorkloadIdentity
metadata:
  name: argocd-application-controller
spec:
  roles: ["roles/container.developer"]
---
apiVersion: gcp.nvoss.demo.altostrat.com/v1alpha1
kind: WorkloadIdentity
metadata:
  name: argocd-image-updater
spec:
  roles: ["roles/artifactregistry.reader"]
