---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dogcat-dev
  annotations:
    # argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-applications-write
    # argocd-image-updater.argoproj.io/git-branch: main # can also be separate target, e.g. base:target
    # argocd-image-updater.argoproj.io/image-list: dogcat=europe-west3-docker.pkg.dev/nvoss-dogcat-ch02-shared/images/dogcat
    # argocd-image-updater.argoproj.io/dogcat.update-strategy: latest
    # argocd-image-updater.argoproj.io/dogcat.allow-tags: "regexp:^[0-9a-f]{40}$"
spec:
  destination:
    namespace: "dogcat"
    name: cluster-dev
  project: cluster-dev
  source:
    path: "chapter02b/config/overlays/dev"
    repoURL: "git@github.com:NucleusEngineering/dogcat.git"
    targetRevision: "HEAD"
    kustomize:
      images:
      - "dogcat=europe-west3-docker.pkg.dev/nvoss-dogcat-ch02-shared/images/dogcat:ca0e346df8f789f6d91db409a8cf7574b421cc9e"
  syncPolicy:
    automated: {}
