---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dogcat-dev
spec:
  destination:
    namespace: "dogcat"
    name: cluster-dev
  project: cluster-dev
  source:
    path: "chapter02b/config/overlays/dev"
    repoURL: "git@github.com:NucleusEngineering/dogcat.git"
    targetRevision: "HEAD"
  syncPolicy:
    automated: {}
