---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-dev
spec:
  destination:
    namespace: "kyverno"
    name: cluster-dev
  project: cluster-dev
  source:
    path: "config/kyverno"
    repoURL: "git@github.com:NucleusEngineering/dogcat-applications.git"
    targetRevision: "HEAD"
  syncPolicy:
    automated: {}
