---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-dev
spec:
  destination:
    namespace: "kyverno"
    name: cluster-dev
  project: cluster-dev
  source:
    path: "config/kyverno"
    repoURL: "git@github.com:NucleusEngineering/dogcat-applications.git"
    targetRevision: "HEAD"
  syncPolicy:
    # CRDs to large to apply, so kubectl create/replace have to be used.
    # Rather than setting this, the user should sync with replace option
    # once to get the CRDs installed and not use below option.
    syncOptions:
    - Replace=true
    automated: {}
