apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
- workloadidentities.yaml
- https://github.com/cert-manager/cert-manager/releases/download/v1.12.0/cert-manager.yaml

patchesStrategicMerge:
- delete-obsolete-serviceaccounts.yaml
