---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipelines
spec:
  destination:
    namespace: "tekton"
    server: "https://kubernetes.default.svc"
  project: cluster-shared
  source:
    path: "config/pipelines"
    repoURL: "git@github.com:NucleusEngineering/dogcat-applications.git"
    targetRevision: "HEAD"
  syncPolicy:
    automated: {}
