apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tekton

resources:
- trigger-github.yaml
- task-git-clone.yaml
- task-kaniko.yaml
- pipeline-example.yaml
- pipeline-dogcat.yaml

