apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: tekton-trigger-secret
spec:
  forProvider:
    source: Inline
    module: |
      resource "random_password" "tekton_trigger_secret" {
        length  = 64
        special = true
      }
      resource "kubernetes_secret_v1" "tekton_trigger_secret" {
        metadata {
          name = "tekton-trigger-secret"
          namespace = "tekton"
        }

        data = {
          "shared-secret" = random_password.tekton_trigger_secret.result
        }
      }
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-triggers-eventlistener-binding
subjects:
  - kind: ServiceAccount
    name: tekton-triggers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-triggers-eventlistener-clusterbinding
subjects:
  - kind: ServiceAccount
    name: tekton-triggers
    namespace: tekton
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-listener
spec:
  serviceAccountName: tekton-triggers
  triggers:
    - name: github-listener
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: tekton-trigger-secret
                secretKey: shared-secret
            - name: "eventTypes"
              value: [ "push" ]
        - ref:
            name: "cel"
          params:
          - name: "overlays"
            value:
            - key: image_tag
              expression: "body.ref.startsWith('refs/tags/') ? body.ref.split('/')[2] : body.head_commit.id"
      bindings:
        - ref: github-binding
      template:
        ref: github-template
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-binding
spec:
  params:
    - name: repoName
      value: $(body.repository.name)
    - name: repoRevision
      value: $(body.head_commit.id)
    - name: repoURL
      value: git@github.com:NucleusEngineering/$(body.repository.name).git # REPLACEME
    - name: image
      value: europe-west3-docker.pkg.dev/nvoss-dogcat-ch02-shared/images/$(body.repository.name):$(extensions.image_tag) # REPLACEME
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: github-template
spec:
  params:
    - name: repoName
    - name: repoRevision
    - name: repoURL
    - name: image
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: $(tt.params.repoName)-run-
      spec:
        serviceAccountName: tekton
        pipelineRef:
          name: $(tt.params.repoName)
        params:
          - name: repoRevision
            value: $(tt.params.repoRevision)
          - name: repoURL
            value: $(tt.params.repoURL)
          - name: image
            value: $(tt.params.image)
        podTemplate:
          securityContext:
            fsGroup: 65532
          nodeSelector:
            cloud.google.com/gke-spot: "true"
        workspaces:
        - name: shared-data
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 4Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: github-listener
  annotations:
    "cert-manager.io/cluster-issuer": "letsencrypt"
spec:
  rules:
  - host: "trigger.tekton.shared.dogcat.nvoss.demo.altostrat.com" # REPLACEME
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: el-github-listener
            port:
              number: 8080
  tls:
  - hosts:
      - "trigger.tekton.shared.dogcat.nvoss.demo.altostrat.com" # REPLACEME
    secretName: github-listener-tls
