---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton
spec:
  destination:
    namespace: "tekton"
    server: {{ .Values.destination.server }}
  project: cluster-shared
  source:
    path: "config/tekton"
    repoURL: "git@github.com:NucleusEngineering/dogcat-applications.git"
    targetRevision: "HEAD"
  syncPolicy:
    automated: {}
