apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: helm-push
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.17.0"
    tekton.dev/categories: Helm
    tekton.dev/tags: helm
    tekton.dev/displayName: "Package and push Helm chart"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    This Task packages and pushes a Helm chart to a GCS bucket.
  params:
    - name: image
      description: TODO
    - name: version
      description: TODO
    - name: chartmuseumURL
      description: TODO
    - name: path
      description: TODO
    - name: builderImage
      description: The image on which builds will run
      default: alpine/helm:3.11.1
  workspaces:
    - name: source
      description: Holds the Helm chart at the specified path.
  steps:
    - name: package-and-push
      resources:
        requests:
          cpu: "1"
          memory: "2Gi"
          ephemeral-storage: "2Gi"
        limits:
          cpu: "1"
          memory: "2Gi"
          ephemeral-storage: "2Gi"
      workingDir: $(workspaces.source.path)
      image: $(params.builderImage)
      script: |
        #!/bin/sh
        set -euo pipefail
        apk --no-cache add curl

        cd $(params.path)
        image_repo="`printf '%s\n' "$(params.image)" | cut -d':' -f1`"
        image_repo_esc="`printf '%s\n' "${image_repo}" | sed 's/[&/\]/\\&/g'`"
        image_tag="`printf '%s\n' "$(params.image)" | cut -d':' -f2`"

        sed -i "s/repository: dogcat/repository: \"${image_repo_esc}\"/g" values.yaml
        sed -i "s/tag: \"\"/tag: \"${image_tag}\"/g" values.yaml

        helm package --version=$(params.version) .
        curl --data-binary "@`find . -type f -name '*.tgz'`" $(params.chartmuseumURL)/api/charts
