apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dogcat-dev
  # annotations:
  #   argocd-image-updater.argoproj.io/image-list: dogcat=europe-west3-docker.pkg.dev/nvoss-dogcat-chapter02-shared/images/dogcat
  #   argocd-image-updater.argoproj.io/dogcat.update-strategy: latest
  #   argocd-image-updater.argoproj.io/dogcat.allow-tags: "regexp:^[0-9a-f]{40}$"
spec:
  destination:
    namespace: dogcat
    server: {{ .Values.destination.server }}
  project: cluster-dev
  sources:
  - repoURL: '{{ .Values.chartmuseum.url }}'
    chart: dogcat
    targetRevision: 0.0.0-*
    helm:
      valueFiles:
      - $values/chapter02b/helm/dev.yaml
      parameters:
      - name: "image.repository"
        value: europe-west3-docker.pkg.dev/nvoss-dogcat-chapter02-shared/images/dogcat
  - repoURL: 'git@github.com:NucleusEngineering/dogcat.git'
    targetRevision: HEAD
    ref: values
  syncPolicy:
    automated: {}
