apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.45.0/release.yaml
- https://storage.googleapis.com/tekton-releases/triggers/previous/v0.22.2/release.yaml
- https://storage.googleapis.com/tekton-releases/triggers/previous/v0.22.2/interceptors.yaml
- https://storage.googleapis.com/tekton-releases/dashboard/previous/v0.33.0/release.yaml
- https://storage.googleapis.com/tekton-releases/chains/previous/v0.14.0/release.yaml
- base/workloadidentities.yaml
- base/ingress.yaml
- base/namespace.yaml
- base/chains-config.yaml

patchesStrategicMerge:
- patches/delete-obsolete-serviceaccounts.yaml
- patches/delete-default-chains-config.yaml
- patches/safe-to-evict.yaml
- patches/resources.yaml
