apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
- base/workloadidentities.yaml
- https://github.com/cert-manager/cert-manager/releases/download/v1.12.0/cert-manager.yaml

patchesStrategicMerge:
- patches/delete-obsolete-serviceaccounts.yaml
