apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- base/namespace.yaml
- base/repositories.yaml
- base/applications.yaml
- base/workloadidentities.yaml
- base/ingress.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.2/manifests/install.yaml

patchesStrategicMerge:
- patches/insecure.yaml
- patches/exclusions.yaml
- patches/delete-obsolete-serviceaccounts.yaml
