apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dogcat
spec:
  destination:
    namespace: dogcat
  project: default
  source:
    path: "chapter02b/helm/dogcat"
    repoURL: git@github.com:NucleusEngineering/dogcat.git
    targetRevision: HEAD
    helm:
      releaseName: dogcat
      valueFiles:
      - ../dev.yaml
      parameters:
      - name: "image.repository"
        value: europe-west1-docker.pkg.dev/nvoss-dogcat-chapter02-shared/images/dogcat
      - name: "image.tag"
        value: invalid
  syncPolicy:
    automated: {}
